### ISSUE TITLE
Setting an existing uuid as a traceId

### ISSUE THREAD

**Issue by leoamp** [apache/incubator-zipkin-brave#842]
Hi I am using Spring Sleuth 2.x and brave for tracing details into zipkin. I have an existing  uuid value and would like to set as a traceId while creating trace and span. Is there a way to do?
Few things I tried as an attempt but in vain. 

`
//The below  gwId is coming from an application.
//and want to leave spanId to auto-generated one by Brave.

long gwId=fc10fbd4702c45d08b94ccff8a31d15f; 
TraceContext ctx = TraceContext.newBuilder().traceId(gwId).spanId(0L).build();
Span newSpan = this.tracer.joinSpan(ctx).name(spanName);
try (Tracer.SpanInScope ws = this.tracer.withSpanInScope(newSpan.start())) {
......
}
`
I don't want to create any new header instead I want to update the traceId.
I check the docs but was not able to see any way to get this.
Any suggestions?

**Comment by devinsba** [comment]
@adriancole and @openzipkin/core I think we need an example here, this question is asked a lot.

@leoamp does this help: https://stackoverflow.com/a/53655726/2232476 ?

**Comment by jcchavezs** [comment]
So the trace is 64bits or 128bits represented in hex so not sure uuid could
suit here (probably not). In such cases where correlation to external IDs
are required it is recommended to add them as tags (as you can later search
based on a tag). Does that work for you?

Den fre. 7. des. 2018, 22:04 skrev Brian Devins-Suresh <
notifications@github.com:

**Comment by adriancole** [comment]
@jcchavezs I think the example here was "long gwId=fc10fbd4702c45d08b94ccff8a31d15f;" so it is hex not really UUID.

Anyway, the only nice way to control the trace ID without headers is use a TraceIdContext. Frankly, I don't want to encourage this behaviour further by adding more apis than what we have.

TraceContextOrSamplingFlags.create(TraceIdContext).. then use any command that accepts TraceContextOrSamplingFlags

**Comment by leoamp** [comment]
Thanks @adriancole @devinsba @jcchavezs  for replying.
Actually, it was a typo and its a hex uuid string (after removing the hyphens to suit my requirement).

1. I gave an attempt to try with a sample long value like,
`TraceIdContext traceIdContext = TraceIdContext.newBuilder().traceId(12345L).build();
 TraceContextOrSamplingFlags traceCtxSampling = TraceContextOrSamplingFlags.create(traceIdContext);      `
but it accepts as long so may not be right option to try for my case.

2. I will try with B3Propagation and will check whether 'traceId(12345L)' can start accepting string hex as an argument.
3. I have added the correlationId in tags as well as annotate them using annotate(..) but some times the annotates won't appear whenever my internal service throws some exception.

**Comment by adriancole** [comment]
ps correlation ids usually are tag not annotations.

**Comment by maxb3k** [comment]
I have the same requirements as @leoamp described. On a TraceContext level trace id is just a couple of longs so UUID 128bit can be encoded to string and back using custom Propagation approach. But then the thing is that SpanReporter rely on TraceContext.traceIdString() which is not customizable at all. SpanAdjuster also operate with already encoded string. I didn't find any consistent API to solve this task.

**Comment by adriancole** [comment]
the reason you are not finding a way to override the default identifier
syntax is because we intentionally do not support it.

there are ways to propagate, make available and possibly generate a
correlated id.

however changing the default syntax and generation is still unlikely to
become a feature.

**Comment by maxb3k** [comment]
Thanks for the quick responding! I feel like i'm missing sleuth design considerations. Can you please point it out somewhere? Ideally it would be like a customization subsection in documentation of what we don't allow you to customize and why. I came to sleuth because of all the spring instrumentations. But i wanted to use UUID as a correlationId and to have customizable header names. And i see how it can be done but it looks more like hacking not customizing.

**Comment by adriancole** [comment]
uuid correlation is a normal feature, supported from a very long time. While this project is not sleuth, sleuth has documentation on how to propagate correlation IDs. It is very common to propagate correlation IDs.
https://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_propagating_extra_fields

The propagation system of brave is pluggable. For example, we support amazon and google formats also. However, UUID syntax is not something supported OOB.

As mentioned in the issue template, we use issues for changes to code, not general question and answer sessions. This type of traffic spams all the watchers of this repository also.

about sleuth please chat here https://gitter.im/spring-cloud/spring-cloud-sleuth
about brave specifics please chat here https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment]
for reference, here's an example of propagation which uses wildly different format than b3 https://github.com/openzipkin/zipkin-aws/blob/master/brave-propagation-aws/src/main/java/brave/propagation/aws/AWSPropagation.java
