### ISSUE TITLE
kafka-streams integration-tests

### ISSUE THREAD

**Issue by jorgheymans** [apache/incubator-zipkin-brave#902]
@jeqo something i noticed during the filter() implementation is that https://github.com/openzipkin/brave/blob/3f84fa27e8bb76eaf29e4d41b79fcbd695dda0e3/instrumentation/kafka-streams/src/test/java/brave/kafka/streams/ITKafkaStreamsTracing.java#L1005 is not returning a tracing producer. Should this be changed to be a tracing producer (and fix all the tests because there will be an additional PRODUCER span) or just rename the method to `createProducer`. 

There's possibly a bit of value in making it a real tracing producer because I think it would effectively test the `KafkaStreamsTracing#nextSpan` https://github.com/openzipkin/brave/blob/3f84fa27e8bb76eaf29e4d41b79fcbd695dda0e3/instrumentation/kafka-streams/src/main/java/brave/kafka/streams/KafkaStreamsTracing.java#L309 

WDYT ?

**Comment by adriancole** [comment]
we should be very careful which types to expose public. right now types are
hidden which lowers the surface area of apis which can break code. I don't
think it will be better to expose and have people cast into N TracingX
types vs use the KafkaTracing object to handle the nextSpan logic.

**Comment by jorgheymans** [comment]
`createTracingProducer` is a helper method in an integration test class though, not really part of the api surface right ?

**Comment by adriancole** [comment]
sorry I didn't notice that. sure.

**Comment by jeqo** [comment]
Sorry for the late reply @jorgheymans 
Renaming to `createProducer` will probably be enough.
As by testing `nextSpan`, `https://github.com/apache/incubator-zipkin-brave/blob/3f84fa27e8/instrumentation/kafka-streams/src/test/java/brave/kafka/streams/KafkaStreamsTracingTest.java` might be already covering this API.
