### ISSUE TITLE
TracingConsumer can not poll message from kafka

### ISSUE THREAD

**Issue by jang675953** [apache/incubator-zipkin-brave#922]
## Describe the Bug
A clear and concise description of what the bug is. If you have a solution in mind, skip raising an issue and open a pull request instead.

when i send to message to kafka using TracingProducer, I poll message from kafka using TracingConsumer and get nothing

![image](https://user-images.githubusercontent.com/20883097/59284675-3ea1f180-8c9f-11e9-8e13-dc230d68216d.png)

and there is no spans about consumer.

## Steps to Reproduce

first: Using TracingProducer to send message to kafka (report to zipkin);
sencond: Using TracingProducer to send message to kafka (report to zipkin);

## Expected Behaviour
The best is to spend some time to write a failing test. Bugs with tests get fixed and stay fixed.
i can see the message polled from kafka and find the span on zipkin

**Comment by adriancole** [comment]
hi this is probably more support in nature. Can you use gitter instead? when you go there, please tell us where your demo code is (maybe it is in github). possibly there is a configuration mistake https://gitter.im/openzipkin/zipkin

**Comment by jang675953** [comment]
here is the demo project，when i use kafka native api，everything goes well.




------------------ 原始邮件 ------------------
发件人: "Adrian Cole"<notifications@github.com>; 
发送时间: 2019年6月12日(星期三) 上午8:08
收件人: "apache/incubator-zipkin-brave"<incubator-zipkin-brave@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [apache/incubator-zipkin-brave] TracingConsumer can not pollmessage from kafka (#922)




Closed #922.
 
&mdash;
